import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/**
 * Represents a user in the system.
 * The User entity is used to store user details such as name, username, password, and role.
 * The default role is set to 'visitor' if no role is provided.
 */
@Entity()
export class User {
    // The unique identifier for the user.
    // Automatically generated by the database.
    @PrimaryGeneratedColumn()
    userID: number;

    // The first name of the user.
    // This field is required for user identification.
    @Column()
    firstName: string;

    // The last name of the user.
    // This field is required for user identification.
    @Column()
    lastName: string;

    // The username of the user.
    // This field is required for user login and identification.
    @Column()
    username: string;

    // The password of the user.
    // This field is required for user authentication.
    @Column()
    password: string;

    // The role of the user.
    // The default role is set to 'visitor' if no role is provided.
    @Column({ default: 'visitor' })
    role: string;
}
